import type { AiAnalysis, RuleSettings, TradeWithAnalysis } from "@/lib/supabase/types";

export const demoUserId = "demo-user";

export const demoRules: RuleSettings = {
  id: "demo-rules",
  user_id: demoUserId,
  max_risk_percent: 1,
  min_rr: 2,
  allowed_sessions: ["London", "New York"],
  allowed_pairs: ["XAUUSD", "EURUSD", "GBPUSD"],
  allowed_directions: ["long", "short"],
  confirmation_required: true,
  require_screenshot: false,
  max_trades_per_day: 3,
  strict_mode: false,
  custom_rules: [
    "Only enter after liquidity sweep and confirmation close",
    "Do not trade within 15 minutes of high-impact news",
    "Stop trading for the day after two losses",
  ],
  notes: "Only take A setups after journaling the reason for entry.",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const demoAnalysis: AiAnalysis = {
  id: "demo-analysis",
  trade_id: "demo-trade-1",
  user_id: demoUserId,
  setup_quality_score: 78,
  discipline_score: 72,
  strengths: ["Clear liquidity sweep noted before entry", "Risk stayed near the plan"],
  weaknesses: ["Entry was slightly early", "Exit criteria could be more specific"],
  detected_mistakes: ["Entered before full confirmation candle close"],
  rule_violations: ["Confirmation required"],
  emotional_observations: ["Mild fear of missing out appears in the notes"],
  improvement_suggestions: [
    "Wait for the confirmation close before entering",
    "Write invalidation before placing risk",
  ],
  recurring_mistakes: ["Early entries", "Moving from observation into action too quickly"],
  model: "mock",
  created_at: new Date().toISOString(),
};

export const demoTrades: TradeWithAnalysis[] = [
  {
    id: "demo-trade-1",
    user_id: demoUserId,
    pair: "XAUUSD",
    direction: "long",
    entry_price: 2344.5,
    stop_loss: 2338.2,
    take_profit: 2359.6,
    risk_percent: 0.8,
    rr: 2.4,
    session: "London",
    emotions: "focused,impatient",
    notes: "Liquidity sweep into demand. Entered after reclaim but before candle close.",
    confirmation: false,
    status: "closed",
    outcome: "win",
    closed_at: new Date("2026-05-12T12:10:00.000Z").toISOString(),
    close_price: 2354.1,
    profit_loss_percent: 1.3,
    profit_loss_amount: 260,
    final_rr: 1.8,
    closing_notes: "Scaled out after London continuation slowed.",
    review_status: "reviewed",
    review_completed_at: new Date("2026-05-12T12:20:00.000Z").toISOString(),
    lot_size: null,
    commission: null,
    swap: null,
    screenshot_url: null,
    checklist_results: [],
    passed_rules: [],
    failed_rules: [],
    checklist_completion_rate: 86,
    discipline_score: 72,
    trade_taken_at: new Date("2026-05-12T09:15:00.000Z").toISOString(),
    trade_timezone: "Europe/London",
    mt5_ticket: null,
    mt5_account: null,
    mt5_broker: null,
    synced_from_mt5: false,
    last_synced_at: null,
    mt5_raw_data: null,
    created_at: new Date("2026-05-12T09:15:00.000Z").toISOString(),
    updated_at: new Date("2026-05-12T09:15:00.000Z").toISOString(),
    ai_analysis: [demoAnalysis],
  },
  {
    id: "demo-trade-2",
    user_id: demoUserId,
    pair: "EURUSD",
    direction: "short",
    entry_price: 1.0832,
    stop_loss: 1.085,
    take_profit: 1.0796,
    risk_percent: 1.4,
    rr: 1.6,
    session: "New York",
    emotions: "frustrated,fomo",
    notes: "Shorted the retest but size was above plan and RR was below minimum.",
    confirmation: true,
    status: "closed",
    outcome: "loss",
    closed_at: new Date("2026-05-11T16:05:00.000Z").toISOString(),
    close_price: 1.085,
    profit_loss_percent: -1.4,
    profit_loss_amount: -280,
    final_rr: -1,
    closing_notes: "Stopped out after entering below planned RR.",
    review_status: "reviewed",
    review_completed_at: new Date("2026-05-11T16:12:00.000Z").toISOString(),
    lot_size: null,
    commission: null,
    swap: null,
    screenshot_url: null,
    checklist_results: [],
    passed_rules: [],
    failed_rules: ["Risk too high", "Minimum RR not met"],
    checklist_completion_rate: 57,
    discipline_score: 41,
    trade_taken_at: new Date("2026-05-11T14:40:00.000Z").toISOString(),
    trade_timezone: "America/New_York",
    mt5_ticket: null,
    mt5_account: null,
    mt5_broker: null,
    synced_from_mt5: false,
    last_synced_at: null,
    mt5_raw_data: null,
    created_at: new Date("2026-05-11T14:40:00.000Z").toISOString(),
    updated_at: new Date("2026-05-11T14:40:00.000Z").toISOString(),
    ai_analysis: [
      {
        ...demoAnalysis,
        id: "demo-analysis-2",
        trade_id: "demo-trade-2",
        setup_quality_score: 54,
        discipline_score: 41,
        rule_violations: ["Risk too high", "Minimum RR not met", "Possible revenge trade"],
      },
    ],
  },
  {
    id: "demo-trade-3",
    user_id: demoUserId,
    pair: "GBPJPY",
    direction: "long",
    entry_price: 193.24,
    stop_loss: 192.9,
    take_profit: 193.95,
    risk_percent: 0.7,
    rr: 2.1,
    session: "Asia",
    emotions: "calm",
    notes: "Took a continuation entry outside preferred session.",
    confirmation: true,
    status: "closed",
    outcome: "breakeven",
    closed_at: new Date("2026-05-10T06:20:00.000Z").toISOString(),
    close_price: 193.25,
    profit_loss_percent: 0,
    profit_loss_amount: 0,
    final_rr: 0,
    closing_notes: "Closed at breakeven after momentum faded.",
    review_status: "reviewed",
    review_completed_at: new Date("2026-05-10T06:28:00.000Z").toISOString(),
    lot_size: null,
    commission: null,
    swap: null,
    screenshot_url: null,
    checklist_results: [],
    passed_rules: [],
    failed_rules: ["Entered outside allowed session"],
    checklist_completion_rate: 71,
    discipline_score: 63,
    trade_taken_at: new Date("2026-05-10T03:05:00.000Z").toISOString(),
    trade_timezone: "Asia/Tokyo",
    mt5_ticket: null,
    mt5_account: null,
    mt5_broker: null,
    synced_from_mt5: false,
    last_synced_at: null,
    mt5_raw_data: null,
    created_at: new Date("2026-05-10T03:05:00.000Z").toISOString(),
    updated_at: new Date("2026-05-10T03:05:00.000Z").toISOString(),
    ai_analysis: [
      {
        ...demoAnalysis,
        id: "demo-analysis-3",
        trade_id: "demo-trade-3",
        setup_quality_score: 67,
        discipline_score: 63,
        rule_violations: ["Entered outside allowed session"],
      },
    ],
  },
];
